name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main # change if using `master`

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Linter
        run: |
          pip install flake8
          flake8 . --exclude=migrations

      - name: Run Tests
        run: |
          python manage.py test

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
          ECR_REPOSITORY: ai-learning-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to AWS App Runner
        uses: aws-actions/aws-apprunner-deploy@v1
        with:
          service-name: ai-learning-app-service
          image-repository-type: ECR
          image-identifier: ${{ secrets.AWS_ECR_REGISTRY }}/ai-learning-app:${{ github.sha }}
          access-role-arn: ${{ secrets.AWS_APP_RUNNER_ROLE }}
